{% set name = "shillelagh" %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/shillelagh-{{ version }}.tar.gz
  sha256: 3d905dd89ef33a8b7b1d745f044943b5ca6fa61a0f6b0b817fb9139be407ed5b

build:
  noarch: python
  entry_points:
    - shillelagh = shillelagh.console:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=46.1.0
    - setuptools-scm >=5
    - wheel
    - pyscaffold >=3.2a0
    - pip
  run:
    - python >=3.8
    - importlib-metadata
    - apsw >=3.9.2
    - python-dateutil >=2.8.1
    - requests >=2.25.1
    - sqlalchemy >=1.3
    - greenlet >=2.0.2
    - typing-extensions >=3.7.4.3
    - packaging


test:
  imports:
    - shillelagh
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/betodealmeida/shillelagh/
  summary: Making it easy to query APIs via SQL
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
